parameters:
#    cornichon_forum.example.class: Cornichon\ForumBundle\Example

services:
#    cornichon_forum.example:
#        class: %cornichon_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
